---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blue
resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
configMapGenerator:
  - name: blue-config
    envs:
      - .env
