# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on:
  pull_request:
    types: [labeled]
name: Build, push, and deploy
env:
  SERVICE: ${{ secrets.SERVICE }}
  TARGET_IMAGE: ${{ secrets.TARGET_IMAGE }}
jobs:
  docker:
    name: Build and push Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: docker login
      uses: actions/docker/login@master
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: docker build
      uses: actions/docker/cli@master
      with:
        args: build -t $SERVICE .
    - name: docker tag
      uses: actions/docker/tag@master
      with:
        args: $SERVICE $TARGET_IMAGE
    - name: docker push sha
      uses: actions/docker/cli@master
      with:
        args: push $TARGET_IMAGE:$IMAGE_SHA
  deploy:
    name: Deploy to Cluster
    runs-on: ubuntu-latest
    needs: docker
    env:
      CLUSTER_REPO: ${{ secrets.CLUSTER_REPO }}
    steps:
    - uses: actions/checkout@master
    - name: Kustomized Namespace - Create Overlay
      uses: zyngl/create_kustomized_namespace@v0.9.0
      env:
        TOKEN: ${{ secrets.TOKEN }}
